Course: **Deep Learning**

Program: **MBA Tech AI**

Sem: **V**

Academic Year: **2024 - 2025**

Instructor: **Dr. Radhika Chapaneri**

Experiment Number: **1**

Roll No: **R013**

Name: **Dhruv Pithadia**

Batch: **B1**

Date of Experiment: **18/07/2024**

Task 1: **Perform Basic operations of tensorflow**

In [2]:
import numpy as np
import tensorflow as tf

tf.__version__

'2.16.1'

In [8]:
#Constants
x = tf.constant([[1,2,3],[4,5,6]])
print(x)
print("x shape: ", x.shape)
print("x datatype: ", x.dtype)
print("x value: ", x.numpy)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
x shape:  (2, 3)
x datatype:  <dtype: 'int32'>
x value:  <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>>


In [10]:
#Variables
var = tf.Variable([0, 0, 0])
var.assign([1,2,3])
print(var)
var.assign_add([1,1,1])


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [11]:
#Operations in tensorflow
#Column Concatenation
A = tf.constant([[3,4,5], [1,2,3]])
B = tf.Variable([[1,1,1], [7,8,9]])
AB_concat_Col = tf.concat([A,B], axis=1)
print(AB_concat_Col.numpy)



<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[3, 4, 5, 1, 1, 1],
       [1, 2, 3, 7, 8, 9]], dtype=int32)>>


In [12]:
#Row Concatenation
A = tf.constant([[3,4,5], [1,2,3]])
B = tf.Variable([[1,1,1], [7,8,9]])
AB_concat_Row = tf.concat([A,B], axis=0)
print(AB_concat_Row.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]], dtype=int32)>>


In [21]:
tf.reshape(AB_concat_Row, [1,12])

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[3, 4, 5, 1, 2, 3, 1, 1, 1, 7, 8, 9]], dtype=int32)>

In [36]:
#Operations
a = tf.constant(2.0)
b = tf.constant(5.1)
c = tf.constant(4.7)

add = tf.add(a,b)
multiply = tf.multiply(a,b)
print("Add: ", add.numpy())
print("Multiply: ", multiply.numpy())

Add:  7.1
Multiply:  10.2


In [42]:
#Operations Reduce Mean
x = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
a = tf.reduce_mean(x)
b = tf.reduce_mean(x, 0)
c = tf.reduce_mean(x, 1)
d = tf.reduce_mean(x, keepdims=True, axis=0)
print(a.numpy())
print(b.numpy())
print(c.numpy())
print(d.numpy())

3.5
[2.5 3.5 4.5]
[2. 5.]
[[2.5 3.5 4.5]]


In [48]:
mysum = tf.reduce_sum([a])
print(mysum.numpy())

3.5


Task 2: **Linear Algebra**

In [59]:
C = tf.constant([[1,2],[3,4]])
print(tf.transpose(C))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [62]:
x = tf.constant(4.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = x**3
grad = tape.gradient(y,x)
print(grad.numpy())

48.0


In [64]:
x = tf.Variable(4.0, trainable=True)
with tf.GradientTape() as tape:
    y = x**3
grad = tape.gradient(y,x)
print(grad.numpy())

48.0


In [66]:
#Higher order derivatives
x = tf.Variable(4.0, trainable=True)
with tf.GradientTape() as tape1:
    with tf.GradientTape() as tape2:
        y = x**3
        order_1 = tape2.gradient(y,x)
    order_2 = tape1.gradient(order_1, x)

print(order_1.numpy())
print(order_2.numpy())

48.0
24.0


Task 4: Compute WX + b where W, x and b are drawn from a random noral distribution. W is of shape (4,3), X is (3,1) and b is (4,1)

In [67]:
tf.random.set_seed(42)

shape_W = (4, 3)
shape_X = (3, 1)
shape_b = (4, 1)

W = tf.random.normal(shape_W)
X = tf.random.normal(shape_X)
b = tf.random.normal(shape_b)

result = tf.matmul(W, X) + b

print("W:\n", W.numpy())
print("X:\n", X.numpy())
print("b:\n", b.numpy())
print("Result (WX + b):\n", result.numpy())

W:
 [[ 0.3274685  -0.8426258   0.3194337 ]
 [-1.4075519  -2.3880599  -1.0392479 ]
 [-0.5573232   0.539707    1.6994323 ]
 [ 0.28893656 -1.5066116  -0.26454744]]
X:
 [[ 0.08422458]
 [-0.86090374]
 [ 0.37812304]]
b:
 [[-0.55909735]
 [-0.5347214 ]
 [ 2.3730333 ]
 [-1.5725931 ]]
Result (WX + b):
 [[ 0.3146885]
 [ 1.0096543]
 [ 2.5040517]
 [-0.3512416]]


Taskk 5: Find the derivative of sigmoid function

In [68]:
def sigmoid(x):
    return 1 / (1 + tf.exp(-x))

@tf.function
def sigmoid_derivative(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = sigmoid(x)
    dy_dx = tape.gradient(y, x)
    return dy_dx

x = tf.constant(1.0)
derivative = sigmoid_derivative(x)

print("x:", x.numpy())
print("Sigmoid(x):", sigmoid(x).numpy())
print("Derivative of Sigmoid at x:", derivative.numpy())

x: 1.0
Sigmoid(x): 0.7310586
Derivative of Sigmoid at x: 0.19661194
